
# theme locaton
# - builtin themes first (packaged in the module)
# - in the curent directory
# - in your user dir ~./ttygif/$name.theme


# root section, no name
# name               -> the name of this template. Ignored for now, but will be used to load templates in future.
# foreground         -> the initial terminal text letter  color
# background         -> the initial terminal text background color
# default_foreground -> the initial terminal reset letter color      (used when things like buffer swaps or clear screns happen)
# default_background -> the initial terminal reset background  color
# transparent        -> -1 or omit to NOT use transparency. Otherwise the text background color of this theme color index will not be drawn (usually 0-15, normally the default / background color)

name               Template
background         0
foreground         15
default_background 0
default_foreground 15
transparent        0


# TITLE SECTION
#  if set at the CLI with --title "xyz" a title will be drawn with absoloute screen cooridinates 
#
#  x         - > title x position on the image plane
#  y          -> title y position on the image plane
#  font_size  -> terminal title  font size. It's a 1 or 1.5 or 10 all work
#  background -> terminal title font background color
#  foreground -> terminal title font foreground color

title
foreground       40
background       0
font_size        1
x                55          
y                10

# padding section
# moves the drawn terminal area
# adds padding arround it so that overlays dont occlude the terminal
# gives you room to add other image portions arround the terminal
# this does not alter the internal terminal dimentions. But the overall image size.
# left    -> Increases the width  of the image by this amount and pushes the screen to the right by that amount
# top     -> Increases the height of the image by this amount and pushes the screen to the bottom by that amount
# right   -> Increases the width  of the image by this amount and is added AFTER the terminal image to the right
# bottom  -> Increases the height of the image by this amount and is added AFTER the terminal image to the bototm

padding
left        29
top         42
right       25
bottom      25



# layer section
# depth           -> not used. will be used for sorting layer depths
# file            -> file name of gif to open. ONLY GIF's are supported. Save with gimp for best success.
# 6 layers can be used
#     the layers are ordered by order of appearance
#     layers 1,2 are below the terminal rendering
#     layers 3,4,5 are above or ontop of the terminal rendering
# all images when loaded are REMAPPED to the local theme color palette!
# mode            -> how to transform the image. 
#                    copy -> will place one copy at the dst cooridinates
#                    scale -> will stretch the image to the cooridinates. no aspect ratio is maintained. it will stretch
#                    tile  -> the image is just placed from left to right and toip to bottom until the image is covered
#                    9slice -> this method takes 2 rectangles, nested and uses the cooridinates to auto scale an image
#                              - The corners (1,3,7,9) are copied no scaling
#                              - The edges (2,4,6,8) are tiled
#                              - the center (5) is either scaled or tiled
#                              - the outer rectangle is the bounding area within the image to be scaled.
#                              - the inner rectangle defines the geometry
#                              - the dst   rectangle is where describes how to map this to the viewport
#                              - left   auto will map to 0
#                              - top    auto will map to 0
#                              - right  auto will map to images width 
#                              - bottom auto will map to images height 
#                              - cooridinate systems starts at 0, an image of 320 width will be 320 wide but the right most pixel will be 319
#
#                                   +o1---+------+---o2+
#                                   |  1  |   2  |  3  |
#                                   +-----+------+-----+     
#                                   |     |i1  i2|     |  
#                                   |  4  |   5  |  6  |  
#                                   |     |i3  i4|     |  
#                                   +-----+------+-----+     
#                                   |  7  |   8  |  9  |
#                                   +o3---+------+---o4+ 
#                    3slice -> this method takes 2 rectangles, nested and uses the cooridinates to auto scale an image
#                              - The corners (1,3) are copied no scaling
#                              - the center (2) is either scaled or tiled
#                              - the outer rectangle is the bounding area within the image to be scaled.
#                              - the inner rectangle left and right defines the geometry, top and bottom are ignored
#                              - the dst   rectangle is where describes how to map this to the viewport
#                              - left   auto will map to 0
#                              - top    auto will map to 0
#                              - right  auto will map to images width 
#                              - bottom auto will map to images height 
#                                +o1---+--------+---o2+
#                                |  1  |i1  2 i2|  3  |
#                                +03---+--------+---04+     
#  transparent     ->  -1 if you dont want transparency, otherwise the index of the theme color palette to be ignored/now written
#  can be omitted if bounds are image limits, automatic
#  outer-left      -> outer bounds of the source image left  , typicaly  0 for full width   
#  outer-top       -> outer bounds of the source image top   , typicaly  0 for full height
#  outer-right     -> outer bounds of the source image right , typicaly auto for full width
#  outer-bottom    -> outer bounds of the source image bottom, typicaly auto for full height
#  can be omitted if bounds are 33/66% respectivly. automatic
#  inner-left      -> 
#  inner-top       ->
#  inner-right     ->
#  inner-bottom    ->
#  can be omitted if bounds are image limits, automatic
#  dst-left        -> viewport render destination left
#  dst-top         -> viewport render destination top
#  dst-right       -> viewport render destination right
#  dst-bottom      -> viewport render destination bottom


#background
layer
depth           -2
file             /home/nd/repos/ttygif-assets/src_gifs/blood_dragon.gif
mode             scale
transparent      0

# game borders
layer
depth           -1
file             game.gif   
mode             9slice
transparent      0
outer-left       0
outer-top        1
outer-right      156
outer-bottom     107
inner-left       77
inner-top        47   
inner-right      124
inner-bottom     76
dst-left         0
dst-top          0
dst-right        auto
dst-bottom       auto

# alerxt icon
layer
depth            1
file             x.gif   
mode             copy
transparent      2
dst-left         50
dst-top          50

# RGB Indexed color palette
# each row is a color, 0-255
# this is the default xterm palette I found online
# you can omit this if you're using the default palette, its auto appenede to each theme on load unless one is given.
