#!/bin/bash
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font AMI_BIOS          -o  assets/font/preview/AMI_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font AmstradPC1512-2y  -o  assets/font/preview/AmstradPC1512-2y.gif     --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font AmstradPC1512     -o  assets/font/preview/AmstradPC1512.gif        --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_8x14          -o  assets/font/preview/ATI_8x14.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_8x16          -o  assets/font/preview/ATI_8x16.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_8x8-2y        -o  assets/font/preview/ATI_8x8-2y.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_8x8           -o  assets/font/preview/ATI_8x8.gif              --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_9x14          -o  assets/font/preview/ATI_9x14.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_9x16          -o  assets/font/preview/ATI_9x16.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATI_SmallW_6x8    -o  assets/font/preview/ATI_SmallW_6x8.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATT_PC6300-2x     -o  assets/font/preview/ATT_PC6300-2x.gif        --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ATT_PC6300        -o  assets/font/preview/ATT_PC6300.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font CompaqThin_8x14   -o  assets/font/preview/CompaqThin_8x14.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font CompaqThin_8x16   -o  assets/font/preview/CompaqThin_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font CompaqThin_8x8    -o  assets/font/preview/CompaqThin_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font DTK_BIOS-2y       -o  assets/font/preview/DTK_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font DTK_BIOS          -o  assets/font/preview/DTK_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_3270pc        -o  assets/font/preview/IBM_3270pc.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_BIOS-2x       -o  assets/font/preview/IBM_BIOS-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_BIOS-2y       -o  assets/font/preview/IBM_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_BIOS          -o  assets/font/preview/IBM_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_CGA-2y        -o  assets/font/preview/IBM_CGA-2y.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_CGA           -o  assets/font/preview/IBM_CGA.gif              --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_CGAthin-2y    -o  assets/font/preview/IBM_CGAthin-2y.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_CGAthin       -o  assets/font/preview/IBM_CGAthin.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_Conv-2x       -o  assets/font/preview/IBM_Conv-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_Conv-2y       -o  assets/font/preview/IBM_Conv-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_Conv          -o  assets/font/preview/IBM_Conv.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_EGA8-2x       -o  assets/font/preview/IBM_EGA8-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_EGA8          -o  assets/font/preview/IBM_EGA8.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_EGA9-2x       -o  assets/font/preview/IBM_EGA9-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_EGA9          -o  assets/font/preview/IBM_EGA9.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_ISO8          -o  assets/font/preview/IBM_ISO8.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_ISO9          -o  assets/font/preview/IBM_ISO9.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_MDA           -o  assets/font/preview/IBM_MDA.gif              --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PGC-2x        -o  assets/font/preview/IBM_PGC-2x.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PGC           -o  assets/font/preview/IBM_PGC.gif              --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PS2thin1      -o  assets/font/preview/IBM_PS2thin1.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PS2thin2      -o  assets/font/preview/IBM_PS2thin2.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PS2thin3      -o  assets/font/preview/IBM_PS2thin3.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_PS2thin4      -o  assets/font/preview/IBM_PS2thin4.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_VGA8-2x       -o  assets/font/preview/IBM_VGA8-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_VGA8          -o  assets/font/preview/IBM_VGA8.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_VGA9-2x       -o  assets/font/preview/IBM_VGA9-2x.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font IBM_VGA9          -o  assets/font/preview/IBM_VGA9.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ITT_BIOS-2y       -o  assets/font/preview/ITT_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ITT_BIOS          -o  assets/font/preview/ITT_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Kaypro2K-2y       -o  assets/font/preview/Kaypro2K-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Kaypro2K          -o  assets/font/preview/Kaypro2K.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Phoenix_BIOS-2y   -o  assets/font/preview/Phoenix_BIOS-2y.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Phoenix_BIOS      -o  assets/font/preview/Phoenix_BIOS.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font PhoenixEGA_8x14   -o  assets/font/preview/PhoenixEGA_8x14.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font PhoenixEGA_8x16   -o  assets/font/preview/PhoenixEGA_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font PhoenixEGA_8x8-2y -o  assets/font/preview/PhoenixEGA_8x8-2y.gif    --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font PhoenixEGA_8x8    -o  assets/font/preview/PhoenixEGA_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font PhoenixEGA_9x14   -o  assets/font/preview/PhoenixEGA_9x14.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyNew_225-2y   -o  assets/font/preview/TandyNew_225-2y.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyNew_225      -o  assets/font/preview/TandyNew_225.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyNew_Mono     -o  assets/font/preview/TandyNew_Mono.gif        --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyNew_TV-2y    -o  assets/font/preview/TandyNew_TV-2y.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyNew_TV       -o  assets/font/preview/TandyNew_TV.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyOld_225-2y   -o  assets/font/preview/TandyOld_225-2y.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyOld_225      -o  assets/font/preview/TandyOld_225.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyOld_TV-2y    -o  assets/font/preview/TandyOld_TV-2y.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font TandyOld_TV       -o  assets/font/preview/TandyOld_TV.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ToshibaLCD_8x16   -o  assets/font/preview/ToshibaLCD_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font ToshibaLCD_8x8    -o  assets/font/preview/ToshibaLCD_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_8x14       -o  assets/font/preview/Verite_8x14.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_8x16       -o  assets/font/preview/Verite_8x16.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_8x8-2y     -o  assets/font/preview/Verite_8x8-2y.gif        --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_8x8        -o  assets/font/preview/Verite_8x8.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_9x14       -o  assets/font/preview/Verite_9x14.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Verite_9x16       -o  assets/font/preview/Verite_9x16.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font VGA_SquarePx      -o  assets/font/preview/VGA_SquarePx.gif         --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font VTech_BIOS-2y     -o  assets/font/preview/VTech_BIOS-2y.gif        --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font VTech_BIOS        -o  assets/font/preview/VTech_BIOS.gif           --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Wyse700a-2y       -o  assets/font/preview/Wyse700a-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Wyse700a          -o  assets/font/preview/Wyse700a.gif             --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Wyse700b-2y       -o  assets/font/preview/Wyse700b-2y.gif          --fps 1
python ttygif/tools/gen_charset.py | python -m ttygif.cli --font Wyse700b          -o  assets/font/preview/ Wyse700b.gif            --fps 1