#!/bin/ba--outputs
python ttygif/tools/gen_charset.py AMI_BIOS          | python -m ttygif.cli --font AMI_BIOS          --output  assets/fonts/preview/AMI_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py AmstradPC1512-2y  | python -m ttygif.cli --font AmstradPC1512-2y  --output  assets/fonts/preview/AmstradPC1512-2y.gif     --fps 1
python ttygif/tools/gen_charset.py AmstradPC1512     | python -m ttygif.cli --font AmstradPC1512     --output  assets/fonts/preview/AmstradPC1512.gif        --fps 1
python ttygif/tools/gen_charset.py ATI_8x14          | python -m ttygif.cli --font ATI_8x14          --output  assets/fonts/preview/ATI_8x14.gif             --fps 1
python ttygif/tools/gen_charset.py ATI_8x16          | python -m ttygif.cli --font ATI_8x16          --output  assets/fonts/preview/ATI_8x16.gif             --fps 1
python ttygif/tools/gen_charset.py ATI_8x8-2y        | python -m ttygif.cli --font ATI_8x8-2y        --output  assets/fonts/preview/ATI_8x8-2y.gif           --fps 1
python ttygif/tools/gen_charset.py ATI_8x8           | python -m ttygif.cli --font ATI_8x8           --output  assets/fonts/preview/ATI_8x8.gif              --fps 1
python ttygif/tools/gen_charset.py ATI_9x14          | python -m ttygif.cli --font ATI_9x14          --output  assets/fonts/preview/ATI_9x14.gif             --fps 1
python ttygif/tools/gen_charset.py ATI_9x16          | python -m ttygif.cli --font ATI_9x16          --output  assets/fonts/preview/ATI_9x16.gif             --fps 1
python ttygif/tools/gen_charset.py ATI_SmallW_6x8    | python -m ttygif.cli --font ATI_SmallW_6x8    --output  assets/fonts/preview/ATI_SmallW_6x8.gif       --fps 1
python ttygif/tools/gen_charset.py ATT_PC6300-2x     | python -m ttygif.cli --font ATT_PC6300-2x     --output  assets/fonts/preview/ATT_PC6300-2x.gif        --fps 1
python ttygif/tools/gen_charset.py ATT_PC6300        | python -m ttygif.cli --font ATT_PC6300        --output  assets/fonts/preview/ATT_PC6300.gif           --fps 1
python ttygif/tools/gen_charset.py CompaqThin_8x14   | python -m ttygif.cli --font CompaqThin_8x14   --output  assets/fonts/preview/CompaqThin_8x14.gif      --fps 1
python ttygif/tools/gen_charset.py CompaqThin_8x16   | python -m ttygif.cli --font CompaqThin_8x16   --output  assets/fonts/preview/CompaqThin_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py CompaqThin_8x8    | python -m ttygif.cli --font CompaqThin_8x8    --output  assets/fonts/preview/CompaqThin_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py DTK_BIOS-2y       | python -m ttygif.cli --font DTK_BIOS-2y       --output  assets/fonts/preview/DTK_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py DTK_BIOS          | python -m ttygif.cli --font DTK_BIOS          --output  assets/fonts/preview/DTK_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_3270pc        | python -m ttygif.cli --font IBM_3270pc        --output  assets/fonts/preview/IBM_3270pc.gif           --fps 1
python ttygif/tools/gen_charset.py IBM_BIOS-2x       | python -m ttygif.cli --font IBM_BIOS-2x       --output  assets/fonts/preview/IBM_BIOS-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_BIOS-2y       | python -m ttygif.cli --font IBM_BIOS-2y       --output  assets/fonts/preview/IBM_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_BIOS          | python -m ttygif.cli --font IBM_BIOS          --output  assets/fonts/preview/IBM_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_CGA-2y        | python -m ttygif.cli --font IBM_CGA-2y        --output  assets/fonts/preview/IBM_CGA-2y.gif           --fps 1
python ttygif/tools/gen_charset.py IBM_CGA           | python -m ttygif.cli --font IBM_CGA           --output  assets/fonts/preview/IBM_CGA.gif              --fps 1
python ttygif/tools/gen_charset.py IBM_CGAthin-2y    | python -m ttygif.cli --font IBM_CGAthin-2y    --output  assets/fonts/preview/IBM_CGAthin-2y.gif       --fps 1
python ttygif/tools/gen_charset.py IBM_CGAthin       | python -m ttygif.cli --font IBM_CGAthin       --output  assets/fonts/preview/IBM_CGAthin.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_Conv-2x       | python -m ttygif.cli --font IBM_Conv-2x       --output  assets/fonts/preview/IBM_Conv-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_Conv-2y       | python -m ttygif.cli --font IBM_Conv-2y       --output  assets/fonts/preview/IBM_Conv-2y.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_Conv          | python -m ttygif.cli --font IBM_Conv          --output  assets/fonts/preview/IBM_Conv.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_EGA8-2x       | python -m ttygif.cli --font IBM_EGA8-2x       --output  assets/fonts/preview/IBM_EGA8-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_EGA8          | python -m ttygif.cli --font IBM_EGA8          --output  assets/fonts/preview/IBM_EGA8.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_EGA9-2x       | python -m ttygif.cli --font IBM_EGA9-2x       --output  assets/fonts/preview/IBM_EGA9-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_EGA9          | python -m ttygif.cli --font IBM_EGA9          --output  assets/fonts/preview/IBM_EGA9.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_ISO8          | python -m ttygif.cli --font IBM_ISO8          --output  assets/fonts/preview/IBM_ISO8.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_ISO9          | python -m ttygif.cli --font IBM_ISO9          --output  assets/fonts/preview/IBM_ISO9.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_MDA           | python -m ttygif.cli --font IBM_MDA           --output  assets/fonts/preview/IBM_MDA.gif              --fps 1
python ttygif/tools/gen_charset.py IBM_PGC-2x        | python -m ttygif.cli --font IBM_PGC-2x        --output  assets/fonts/preview/IBM_PGC-2x.gif           --fps 1
python ttygif/tools/gen_charset.py IBM_PGC           | python -m ttygif.cli --font IBM_PGC           --output  assets/fonts/preview/IBM_PGC.gif              --fps 1
python ttygif/tools/gen_charset.py IBM_PS2thin1      | python -m ttygif.cli --font IBM_PS2thin1      --output  assets/fonts/preview/IBM_PS2thin1.gif         --fps 1
python ttygif/tools/gen_charset.py IBM_PS2thin2      | python -m ttygif.cli --font IBM_PS2thin2      --output  assets/fonts/preview/IBM_PS2thin2.gif         --fps 1
python ttygif/tools/gen_charset.py IBM_PS2thin3      | python -m ttygif.cli --font IBM_PS2thin3      --output  assets/fonts/preview/IBM_PS2thin3.gif         --fps 1
python ttygif/tools/gen_charset.py IBM_PS2thin4      | python -m ttygif.cli --font IBM_PS2thin4      --output  assets/fonts/preview/IBM_PS2thin4.gif         --fps 1
python ttygif/tools/gen_charset.py IBM_VGA8-2x       | python -m ttygif.cli --font IBM_VGA8-2x       --output  assets/fonts/preview/IBM_VGA8-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_VGA8          | python -m ttygif.cli --font IBM_VGA8          --output  assets/fonts/preview/IBM_VGA8.gif             --fps 1
python ttygif/tools/gen_charset.py IBM_VGA9-2x       | python -m ttygif.cli --font IBM_VGA9-2x       --output  assets/fonts/preview/IBM_VGA9-2x.gif          --fps 1
python ttygif/tools/gen_charset.py IBM_VGA9          | python -m ttygif.cli --font IBM_VGA9          --output  assets/fonts/preview/IBM_VGA9.gif             --fps 1
python ttygif/tools/gen_charset.py ITT_BIOS-2y       | python -m ttygif.cli --font ITT_BIOS-2y       --output  assets/fonts/preview/ITT_BIOS-2y.gif          --fps 1
python ttygif/tools/gen_charset.py ITT_BIOS          | python -m ttygif.cli --font ITT_BIOS          --output  assets/fonts/preview/ITT_BIOS.gif             --fps 1
python ttygif/tools/gen_charset.py Kaypro2K-2y       | python -m ttygif.cli --font Kaypro2K-2y       --output  assets/fonts/preview/Kaypro2K-2y.gif          --fps 1
python ttygif/tools/gen_charset.py Kaypro2K          | python -m ttygif.cli --font Kaypro2K          --output  assets/fonts/preview/Kaypro2K.gif             --fps 1
python ttygif/tools/gen_charset.py Phoenix_BIOS-2y   | python -m ttygif.cli --font Phoenix_BIOS-2y   --output  assets/fonts/preview/Phoenix_BIOS-2y.gif      --fps 1
python ttygif/tools/gen_charset.py Phoenix_BIOS      | python -m ttygif.cli --font Phoenix_BIOS      --output  assets/fonts/preview/Phoenix_BIOS.gif         --fps 1
python ttygif/tools/gen_charset.py PhoenixEGA_8x14   | python -m ttygif.cli --font PhoenixEGA_8x14   --output  assets/fonts/preview/PhoenixEGA_8x14.gif      --fps 1
python ttygif/tools/gen_charset.py PhoenixEGA_8x16   | python -m ttygif.cli --font PhoenixEGA_8x16   --output  assets/fonts/preview/PhoenixEGA_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py PhoenixEGA_8x8-2y | python -m ttygif.cli --font PhoenixEGA_8x8-2y --output  assets/fonts/preview/PhoenixEGA_8x8-2y.gif    --fps 1
python ttygif/tools/gen_charset.py PhoenixEGA_8x8    | python -m ttygif.cli --font PhoenixEGA_8x8    --output  assets/fonts/preview/PhoenixEGA_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py PhoenixEGA_9x14   | python -m ttygif.cli --font PhoenixEGA_9x14   --output  assets/fonts/preview/PhoenixEGA_9x14.gif      --fps 1
python ttygif/tools/gen_charset.py TandyNew_225-2y   | python -m ttygif.cli --font TandyNew_225-2y   --output  assets/fonts/preview/TandyNew_225-2y.gif      --fps 1
python ttygif/tools/gen_charset.py TandyNew_225      | python -m ttygif.cli --font TandyNew_225      --output  assets/fonts/preview/TandyNew_225.gif         --fps 1
python ttygif/tools/gen_charset.py TandyNew_Mono     | python -m ttygif.cli --font TandyNew_Mono     --output  assets/fonts/preview/TandyNew_Mono.gif        --fps 1
python ttygif/tools/gen_charset.py TandyNew_TV-2y    | python -m ttygif.cli --font TandyNew_TV-2y    --output  assets/fonts/preview/TandyNew_TV-2y.gif       --fps 1
python ttygif/tools/gen_charset.py TandyNew_TV       | python -m ttygif.cli --font TandyNew_TV       --output  assets/fonts/preview/TandyNew_TV.gif          --fps 1
python ttygif/tools/gen_charset.py TandyOld_225-2y   | python -m ttygif.cli --font TandyOld_225-2y   --output  assets/fonts/preview/TandyOld_225-2y.gif      --fps 1
python ttygif/tools/gen_charset.py TandyOld_225      | python -m ttygif.cli --font TandyOld_225      --output  assets/fonts/preview/TandyOld_225.gif         --fps 1
python ttygif/tools/gen_charset.py TandyOld_TV-2y    | python -m ttygif.cli --font TandyOld_TV-2y    --output  assets/fonts/preview/TandyOld_TV-2y.gif       --fps 1
python ttygif/tools/gen_charset.py TandyOld_TV       | python -m ttygif.cli --font TandyOld_TV       --output  assets/fonts/preview/TandyOld_TV.gif          --fps 1
python ttygif/tools/gen_charset.py ToshibaLCD_8x16   | python -m ttygif.cli --font ToshibaLCD_8x16   --output  assets/fonts/preview/ToshibaLCD_8x16.gif      --fps 1
python ttygif/tools/gen_charset.py ToshibaLCD_8x8    | python -m ttygif.cli --font ToshibaLCD_8x8    --output  assets/fonts/preview/ToshibaLCD_8x8.gif       --fps 1
python ttygif/tools/gen_charset.py Verite_8x14       | python -m ttygif.cli --font Verite_8x14       --output  assets/fonts/preview/Verite_8x14.gif          --fps 1
python ttygif/tools/gen_charset.py Verite_8x16       | python -m ttygif.cli --font Verite_8x16       --output  assets/fonts/preview/Verite_8x16.gif          --fps 1
python ttygif/tools/gen_charset.py Verite_8x8-2y     | python -m ttygif.cli --font Verite_8x8-2y     --output  assets/fonts/preview/Verite_8x8-2y.gif        --fps 1
python ttygif/tools/gen_charset.py Verite_8x8        | python -m ttygif.cli --font Verite_8x8        --output  assets/fonts/preview/Verite_8x8.gif           --fps 1
python ttygif/tools/gen_charset.py Verite_9x14       | python -m ttygif.cli --font Verite_9x14       --output  assets/fonts/preview/Verite_9x14.gif          --fps 1
python ttygif/tools/gen_charset.py Verite_9x16       | python -m ttygif.cli --font Verite_9x16       --output  assets/fonts/preview/Verite_9x16.gif          --fps 1
python ttygif/tools/gen_charset.py VGA_SquarePx      | python -m ttygif.cli --font VGA_SquarePx      --output  assets/fonts/preview/VGA_SquarePx.gif         --fps 1
python ttygif/tools/gen_charset.py VTech_BIOS-2y     | python -m ttygif.cli --font VTech_BIOS-2y     --output  assets/fonts/preview/VTech_BIOS-2y.gif        --fps 1
python ttygif/tools/gen_charset.py VTech_BIOS        | python -m ttygif.cli --font VTech_BIOS        --output  assets/fonts/preview/VTech_BIOS.gif           --fps 1
python ttygif/tools/gen_charset.py Wyse700a-2y       | python -m ttygif.cli --font Wyse700a-2y       --output  assets/fonts/preview/Wyse700a-2y.gif          --fps 1
python ttygif/tools/gen_charset.py Wyse700a          | python -m ttygif.cli --font Wyse700a          --output  assets/fonts/preview/Wyse700a.gif             --fps 1
python ttygif/tools/gen_charset.py Wyse700b-2y       | python -m ttygif.cli --font Wyse700b-2y       --output  assets/fonts/preview/Wyse700b-2y.gif          --fps 1
python ttygif/tools/gen_charset.py Wyse700b          | python -m ttygif.cli --font Wyse700b          --output  assets/fonts/preview/Wyse700b.gif             --fps 1